---
title: "Análisis de las condiciones favorables para la ocurrencia de incendios en el Perú para los años 2000 -2019"
author: "Contreras y Flores"
date: "`r format(Sys.time(), '%B %d, %Y')`"
output: 
  pdf_document:
    fig_caption: yes
    latex_engine: xelatex
toc: true
toc_depth: 5
fig_caption: true
mainfont: Times New Roman      
---

# Introducción
Los incendios forestales se han convertido en un problema ambiental de gran relevancia y gravedad en las últimas décadas; se presenta a nivel mundial sobre todo en los países con grandes extensiones de áreas forestales (Sabuco, 2013). Se estima que cada año se producen entre 60 000 y 80 000 incendios forestales, los cuales tienen una gran capacidad destructiva, ya que devastan entre 3 y 10 millones de hectáreas (Bisbal, 2019).

## 1. Identificación del problema

El Perú es un País con una gran biodiversidad, presenta más de un 75% del total del planeta con este potencial, posee una gran extensión del recurso forestal, ubicándose en el segundo
lugar, a nivel de Sudamérica en bosques naturales, y noveno lugar a nivel mundial. (FAO, 2004). De acuerdo a la clasificación de tierras, por su capacidad de uso mayor se tiene al recurso forestal y pastos ocupando la mayor extensión del territorio nacional; el recurso forestal está formado por tierras de producción forestal y tierras de protección donde las tierras de producción están cubiertas de bosques generalmente heterogéneos dedicados a la producción permanente de madera y otros productos forestales y las tierras de protección en la mayoría de casos se encuentran en terrenos montañosos, con pendientes moderadamente empinadas s a altas.


### 1.1. Planteamiento del problema
### 1.2. Objetivos
Generar una metodología para el análisis predictivo de los incendios forestales sobre la cobertura vegetal, a través del análisis de variables que condicionan las características físicas y meteorológicas del territorio nacional. 

#### 1.2.1. Objetivo General

#### 1.2.2. Objetivos Específicos
### 1.3. Justificación

## 2. Antecedentes

## 3. Marco Teórico

## 4. Área de estudio

## 5. Metodología

## 6. Resultados

## 7. Análisis 

## 8. Discusión de resultados

## 9. Conclusión

## 10. Referencias


