---
title: <center> <h1> **Análisis de las condiciones favorables para la ocurrencia de incendios en el Perú para los años 2000 - 2018** </h1> </center>
author: <center> <h2> *Contreras Huerta Julio y Flores Farfan Jair* </h2> </center>
date: "***`r format(Sys.time(), '%B %d, %Y')`***"
output:
  html_document:
    fig_caption: yes
    toc: yes
    toc_depth: 6 
    toc_float:
      collapsed: true 
      smooth_scroll: true 
    number_sections: true
    theme: journal 
    fig_width: 7
    fig_height: 6
---
```{r warning=FALSE, message=FALSE, eval=TRUE}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(sf)
library(rgee)
library(mapedit)
library(raster)
library(cptcity)
library(leaflet)
library(leaflet.extras)
library(leafpop)
library(MASS)
library(dplyr)
library(ncdf4)
library(devtools)
library(velox)
library(signal)
library(foreach)
library(RColorBrewer)
library(reshape2)
```

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Descripción del área de estudio

```{r eval=TRUE, message=FALSE, echo = FALSE, warning=FALSE, cache=FALSE, fig.align='center'}
fires <- st_read('Materiales/registro_incendios_2000_2018.gpkg', quiet = TRUE)

yr <- 2016

# CREACION Y MANIPULACION DE TABLA PARA EL PLOTEO
a <- fires %>% group_by(Date = paste(`AñO`, MES_N, sep = '-')) %>%
  summarise(nfires = length(Date)) %>% 
  group_by(MES = substr(Date,6,7)) %>% 
  summarise(fires_mean = mean(nfires, na.rm = T), fires_max  = max(nfires, na.rm = T)) %>%
  mutate(MES = as.numeric(MES)) %>% arrange(MES) %>% as.data.frame() %>% dplyr::select(-geom)

b <- fires %>% dplyr::filter(`AñO`== yr) %>%
  mutate(MES = MES_N) %>%
  group_by(MES) %>% 
  summarise(fires_anom = length(MES)) %>%
  as.data.frame() %>% dplyr::select(-geom)


df <- data.frame(MES = c(1:12)) %>% 
  full_join(a, by = 'MES') %>% 
  full_join(b, by = 'MES') %>% 
  dplyr::select(-MES) %>%
  mutate(Date = seq(as.Date('2018-01-01'), as.Date('2018-12-01'), by='month'),
         fires_mean = ifelse(is.na(fires_mean), 0, fires_mean),
         fires_max  = ifelse(is.na(fires_max), 0, fires_max),
         fires_anom = ifelse(is.na(fires_anom), 0, fires_anom)) %>%
  melt(id.vars = c("Date")) 

# Nombre leyenda
df$variable <- rep(c("Promedios históricos", "Máximos históricos", "Registro Mensual"), each = 12)
names(df)[2] <- "Incendios"

# Ploteo
ggplot(data = df, aes(x = Date, y = value, fill = Incendios, 
                      color = Incendios, alpha = Incendios)) + 
  geom_bar(stat = "identity", position = "identity") +
  scale_fill_manual(values = c("red", "blue","gray")) + 
  scale_colour_manual(values=c("red", "blue", "black")) +
  scale_alpha_manual(values = c(0.2, 0.4, 0)) +
  ggtitle('Comportamiento Mensual de Incendios',
          subtitle = paste0('Desde 2000 hasta 2018\nAño ', as.character(yr))) +
  theme_test() +
  labs(y = 'Número de incendios', x = '') +
  theme(plot.title    = element_text(size = 20, hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(size = 12, hjust = 0.5, face = 'italic'),
        axis.text.x   = element_text(size = 12, hjust = 1),
        axis.text.y   = element_text(size = 12),
        axis.title.y  = element_text(size = 15, hjust = 0.5, face = 'bold', vjust = 0.5),
        legend.position = c(.2,.75), 
        legend.background = element_rect(fill = "white", 
                                         color = "#fed976", 
                                         linetype = "solid"),
        legend.key = element_rect(fill = "white"),
        legend.key.size = unit(0.5, "cm"),
        legend.key.width = unit(0.3,"cm"),
        legend.margin = margin(0.1, 0.1, 0.1, 0.1, "cm"),
        legend.title = element_text(face = "bold"),
        legend.title.align = 0.5) + 
  scale_x_date(date_labels = "%b", breaks = '1 month') +
  scale_y_continuous(breaks = seq(0,450,50), limits = c(0, 430)) 
```


```{r eval=TRUE, message=FALSE, echo = FALSE, warning=FALSE, fig.align='center', comment='', error=FALSE}
pp_velox <- velox("RasterData/PISCO/PISCOp_v11_area.tif")
region <- st_read("Materiales/area.gpkg", quiet = TRUE)

data <- pp_velox$extract(sp=region, fun = function(x){mean(x,na.rm=T)}) %>%
  as.vector() # Por que no usar max para los maximos (en ese caso seria para cada pixel)

date <- seq(as.Date('1981-01-01'),as.Date('2018-02-01'), by='month')

# df
pp <- data.frame(date, data) %>% 
  mutate(mes = substr(date, 6, 7)) %>% 
  group_by(mes) %>%
  summarise(ppmean = mean(data, na.rm = T), 
            ppmax = max(data, na.rm = T), 
            ppmin = min(data, na.rm=T)) 
names(pp) <- c("mes", "PP media histórica", "PP máxima histórica", "PP mínima histórica")
pp <- melt(pp, id.vars = c("mes")) 

pps <- data.frame(date, value = data) %>% 
  mutate(mes = substr(date, 6, 7)) %>%
  dplyr::filter(substr(date, 1, 4) %in% c(2000, 2005, 2010, 2016)) %>% 
  add_column(variable = rep(c("PP 2000", "PP 2005", "PP 2010", "PP 2016"), each = 12)) %>%
  dplyr::select(-date)

# Union filas
PP <- pp %>% add_row(pps) 
PP$date <- rep(seq(as.Date('2018-01-01'), as.Date('2018-12-01'), by = 'month'), 7)

names(PP)[2] <- "Precipitación [mm]" # name leyenda

# Plot
ggplot(data = PP, aes(x = date, y = value, 
                      fill = `Precipitación [mm]`, color = `Precipitación [mm]`, 
                      alpha = `Precipitación [mm]`, group = `Precipitación [mm]`)) + # , size = variable 
  geom_line(aes(linetype = `Precipitación [mm]`)) +
  geom_point() +
  scale_linetype_manual(values=c("solid", "solid", "solid", "solid", 
                                 "dotted", "twodash", "dotted")) +
  scale_colour_manual(values=c("#e9c612", "#e31a1c", "#54278f", "#3fce1e", 
                               "#0555f4", "black", "#0555f4")) +
  scale_alpha_manual(values = c(1, 1, 1, 1, 1, 1, 1)) +
  # scale_size_manual(values=c(0.2, 0.2, 0.2, 0.2, 0.5, 0.5, 0.5)) +
  theme_test() + 
  ylab(label = '[mm]') +
  xlab(label = '') +
  ggtitle('Precipitacion acumulada mensual', subtitle = 'De 1981 hasta 2018') +
  theme(plot.title = element_text(size = 16, hjust = 0.5, face = 'bold'),
        plot.subtitle = element_text(size=13, hjust=0.5, face = 'italic'),
        axis.text.x = element_text(size=12), 
        axis.text.y = element_text(size=12),
        axis.title = element_text(size=20), 
        axis.title.y =  element_text(size=12, face='bold'),
        legend.position = c(.5,.83), # posicion de la leyenda
        legend.background = element_rect(fill = "white", 
                                         color = "#fed976", 
                                         linetype = "solid"),
        legend.key = element_rect(fill = "white"),
        legend.key.height= unit(0.1, 'cm'), 
        legend.key.width = unit(0.5,"cm"), # ancho de simbolo leyenda
        legend.margin = margin(0.1, 0.1, 0.1, 0.1, "cm"),
        legend.title = element_text(face = "bold", size=8.5), # modificar letra del titulo
        legend.text = element_text(size=7), # tamano letra etiqueta
        legend.title.align = 0.5,
        legend.spacing.y = unit(0.1, "cm")) + # distancia entre titulo legend y los labels
  scale_x_date(date_labels = '%b', breaks = '1 month') + # , breaks = '1 month', date_labels = '%b'
  scale_y_continuous(breaks = seq(0,300,50), limits = c(0, 270)) 
```